name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ai_code_review:
    runs-on: ubuntu-latest

    steps:
    - name: AI Code Review
      uses: AleksandrFurmenkovOfficial/ai-code-review@v0.2.2
      with:
        token: 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 # or your token with access to PRs, read for files and write for comments
        openai_api_key: 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 # You should have access to gpt-4-0613
        owner: DaveloperT
        repo: gpt-code-review-demo
        pr_number: ${{ github.event.number }}
        file_extensions: ".java" # for example
        #exclude_paths: "test/,docs/"     # for example
